language: generic

sudo: required
services:
    - docker

before-install:
    - docker build -t bramvdwaal/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bramvdwaal/docker-react npm run test